### PR TITLE
added background color setters to DrawerFrameLayout

### PR DESCRIPTION
**Pull request by jkwiecien**
Sent PR as you requested ;)

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
Make sure you don't change the code style too much as this makes it difficult to me to see the real changes

**Comment by jkwiecien** [comment]
Cmon, it's just couple spaces ;)

**Comment by HeinrichReimer** [comment]
I'll merge it by hand, when I'm at home later ;)

**Comment by HeinrichReimer** [comment]
I thought it would be better to have the whole drawer themable so I'm currently developing some `DrawerTheme` class and a theme engine.

**Comment by HeinrichReimer** [comment]
The theme engine will allow you to set themes for your drawer and each item/profile. And you can change it in runtime

**Comment by HeinrichReimer** [comment]
Rather than merging many small code changes for theming I made a theming engine that is more flexible.

**Pull request closed without merging**
