### PR TITLE
Update DrawerView.java

### PR DESCRIPTION
**Pull request by SMontiel**
Compile the demo app with two profiles and one draweritem, compile with the version 2.2.0 and the library in this repo just compare it. You 'll see the issues

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
Please describe what this pull request is for. You make two very unclear code changes...

**Comment by SMontiel** [comment]
Watch these videos https://drive.google.com/file/d/0B90o7iqpIsEsTm0xWVpULVpwZGM/view?usp=docslist_api and https://drive.google.com/file/d/0B90o7iqpIsEsOV9YM3pFV3NYMms/view?usp=docslist_api .
My pull request fix that.

**Comment by SMontiel** [comment]
profiles do not change.

**Comment by HeinrichReimer** [comment]
What I don't understand is this change:
````
-    private boolean profileListOpen = false;
+	//Before
+//--private boolean profileListOpen = false;
+	//After Salvador Montiel
+    private boolean profileListOpen = true;
````
That is unlogical since the profile list is closed initially.

**Comment by HeinrichReimer** [comment]
I'll most likely merge this by hand as there are some unneeded comments in your pull request. Thanks for working on this annoying bug! I'll leave the first change as it is now:
````
private boolean profileListOpen = false;
````

**Comment by SMontiel** [comment]
Thanks!. No problemas.

**Comment by SMontiel** [comment]
Thanks! No problem.

**Comment by SMontiel** [comment]
If you don't change this line
```java
private boolean profileListOpen = false;
```
to
```java
private boolean profileListOpen = true;
```
the error is this:
https://drive.google.com/file/d/0B90o7iqpIsEsOV9YM3pFV3NYMms/view

**Comment by SMontiel** [comment]
when switching between profiles, the profile list is shown down of DrawerItems

**Pull request closed without merging**
